#!/bin/zsh
set -euo pipefail

: "${EXPENSES_ENV_FILE:?Set EXPENSES_ENV_FILE to the production env file}"
[[ -f "$EXPENSES_ENV_FILE" ]] || { print -u2 "Environment file does not exist"; exit 1; }

set -a
source "$EXPENSES_ENV_FILE"
set +a

export EXPENSES_DATABASE_PATH="${EXPENSES_DATABASE_PATH:-${DATABASE_PATH:?Set DATABASE_PATH}}"
export EXPENSES_ATTACHMENTS_PATH="${EXPENSES_ATTACHMENTS_PATH:-${ATTACHMENTS_PATH:?Set ATTACHMENTS_PATH}}"
: "${EXPENSES_BACKUP_DESTINATION:?Set EXPENSES_BACKUP_DESTINATION}"
: "${EXPENSES_AGE_RECIPIENT:?Set EXPENSES_AGE_RECIPIENT}"
: "${EXPENSES_BACKUP_SCRIPT:?Set EXPENSES_BACKUP_SCRIPT}"

exec "$EXPENSES_BACKUP_SCRIPT"
